### ISSUE TITLE
Doesn't seem to work with "grid" - wireframe

### ISSUE THREAD

**Issue by unkerjay** [elfnor/generative-art-examples#1]
Spits out an error: 

Example Code:

`p, li { white-space: pre-wrap; }

rule CUBE

{

{ x -5 y 5 z -5 } C000

{ x 5 y 5 z -5 } C001

{ x 5 y -5 z -5 } C011

{ x -5 y -5 z -5 } C010

{ x -5 y 5 z 5 } C100

{ x 5 y 5 z 5 } C101

{ x 5 y -5 z 5 } C111

{ x -5 y -5 z 5 } C110

}

CUBE

//8 CORNERS

rule C000{ CORNER }

rule C001{ { rx 0 ry -90 rz 0 }CORNER }

rule C011{ {rx 180 ry 180 rz 0 }CORNER }

rule C010{ {rx 180 ry 90 rz 0 }CORNER }

rule C100{ {rx 0 ry 90 rz 0 }CORNER }

rule C101{ {rx 0 ry 180 rz 0 }CORNER }

rule C111{ {rx 180 ry -90 rz 0 }CORNER }

rule C110{ {rx 180 ry 0 rz 0 }CORNER }

//ARC

rule ARC maxdepth 30 {

{ z 0.85 y -0.05 rx 6.5 ry 2.8 s 0.975 blend green 0.25 } ARC

grid

}

//CORNER

rule CORNER

{

{ color blue }ARC

{ color blue rx -90 ry 90 }ARC

{ color blue rz 90 ry -90 }ARC

}`

**Comment by kronpano** [comment]
The "entry " rule needs to be at the top
So just move the CUBE line to the top and the parser will work.
